### ISSUE TITLE
Installation fails because of geolite

### ISSUE THREAD

**Issue by ashemsay** [YunoHost-Apps/discourse_ynh#52]
Hello,

I tried installing the application on my fresh yunohost instance but it failed because it cannot resolve geolite.maxmind.com (see logs further down).

Indeed geolite.maxmind.com is not resolvable by my dns server either:

```
dig geolite.maxmind.com @9.9.9.9

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> geolite.maxmind.com @9.9.9.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 59295
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;geolite.maxmind.com.		IN	A

;; AUTHORITY SECTION:
maxmind.com.		2171	IN	SOA	josh.ns.cloudflare.com. dns.cloudflare.com. 2032965390 10000 2400 604800 3600

;; Query time: 27 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Thu Jan 23 20:24:21 CET 2020
;; MSG SIZE  rcvd: 107
```

Installation logs:
```
Warning:
Warning: rake aborted!
Warning: SocketError: Failed to open TCP connection to geolite.maxmind.com:443 (getaddrinfo: Name or service not known)
Warning: /var/www/discourse/lib/final_destination.rb:406:in `safe_session'
Warning: /var/www/discourse/lib/final_destination.rb:357:in `safe_get'
Warning: /var/www/discourse/lib/final_destination.rb:129:in `get'
Warning: /var/www/discourse/lib/file_helper.rb:47:in `download'
Warning: /var/www/discourse/lib/discourse_ip_info.rb:30:in `mmdb_download'
Warning: /var/www/discourse/lib/tasks/assets.rake:239:in `block (3 levels) in <top (required)>'
Warning: /var/www/discourse/lib/tasks/assets.rake:238:in `each'
Warning: /var/www/discourse/lib/tasks/assets.rake:238:in `block (2 levels) in <top (required)>'
Warning:
Warning: Caused by:
Warning: SocketError: getaddrinfo: Name or service not known
Warning: /var/www/discourse/lib/final_destination.rb:406:in `safe_session'
Warning: /var/www/discourse/lib/final_destination.rb:357:in `safe_get'
Warning: /var/www/discourse/lib/final_destination.rb:129:in `get'
Warning: /var/www/discourse/lib/file_helper.rb:47:in `download'
Warning: /var/www/discourse/lib/discourse_ip_info.rb:30:in `mmdb_download'
Warning: /var/www/discourse/lib/tasks/assets.rake:239:in `block (3 levels) in <top (required)>'
Warning: /var/www/discourse/lib/tasks/assets.rake:238:in `each'
Warning: /var/www/discourse/lib/tasks/assets.rake:238:in `block (2 levels) in <top (required)>'
Warning: Tasks: TOP => assets:precompile
Warning: (See full trace by running task with --trace)
Warning: [ERR] !!
Warning:  discourse's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: Please find here an extract of the log before the crash:
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/tasks/assets.rake:239:in `block (3 levels) in <top (required)>'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/tasks/assets.rake:238:in `each'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/tasks/assets.rake:238:in `block (2 levels) in <top (required)>'
Warning: [DEBUG]: WARNING -
Warning: [DEBUG]: WARNING - Caused by:
Warning: [DEBUG]: WARNING - SocketError: getaddrinfo: Name or service not known
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/final_destination.rb:406:in `safe_session'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/final_destination.rb:357:in `safe_get'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/final_destination.rb:129:in `get'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/file_helper.rb:47:in `download'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/discourse_ip_info.rb:30:in `mmdb_download'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/tasks/assets.rake:239:in `block (3 levels) in <top (required)>'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/tasks/assets.rake:238:in `each'
Warning: [DEBUG]: WARNING - /var/www/discourse/lib/tasks/assets.rake:238:in `block (2 levels) in <top (required)>'
Warning: [DEBUG]: WARNING - Tasks: TOP => assets:precompile
Warning: [DEBUG]: WARNING - (See full trace by running task with --trace)
Warning: [DEBUG]: DEBUG   - + ynh_print_err '--message=!!
Warning:   discourse'\''s script has encountered an error. Its execution was cancelled.
Warning: !!'
Warning: [DEBUG]: WARNING - !!
Warning: [DEBUG]: DEBUG   - + local legacy_args=m
Warning: [DEBUG]: WARNING -  discourse's script has encountered an error. Its execution was cancelled.
Warning: [DEBUG]: DEBUG   -=message=)
Warning: [DEBUG]: WARNING - !!
Warning: [DEBUG]: DEBUG   - + declare -Ar args_array
Warning: [DEBUG]: DEBUG   - + local message
Warning: [DEBUG]: DEBUG   - + ynh_handle_getopts_args '--message=!!
Warning:   discourse'\''s script has encountered an error. Its execution was cancelled.
Warning: !!'
Warning: [DEBUG]: DEBUG   - + set +x
Warning: [DEBUG]: DEBUG   - !!
Warning:  discourse'\''s script has encountered an error. Its execution was cancelled.
Warning: !!'
Warning: [DEBUG]: DEBUG   - !!
Warning:  discourse'\''s script has encountered an error. Its execution was cancelled.
Warning: !!'
Warning: [DEBUG]: DEBUG   -'
Warning: [DEBUG]: DEBUG   - + set +x
Warning:
Info: The operation 'Install 'discourse' application' has failed! To get help, please share the full log of this operation using the command 'yunohost log display 20200123-184716-app_install-discourse --share'
Success! The SSOwat configuration has been generated
Error: The operation 'Install 'discourse' application' has failed! To get help, please share the full log of this operation using the command 'yunohost log display 20200123-184716-app_install-discourse --share'
```

**Comment by JimboJoe** [comment]
Please see #51, you have the same issue.
Version 2.3.9 has been released, I need to find time to package and test it.
